info:
  component: api-gateway

server:
  port: 8765

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  cloud:
    consul:
      #instance:
       # preferIpAddress: true
      config:
        enabled: true
        host: localhost
        port: 8500
ribbon:
  eureka:
    enabled: false
  #restclient:
   # enabled: true
zuul:
  #ignoreLocalService: false
  #ignored-services: "*"
  routes:
    employee-producer:
      path: /api/employee-registration/**
      #serviceId: employee-producer
      url: http://localhost:8098/api/employee-registration
    employee-search:
      path: /api/employee-search/**
      serviceId: employee-search
      
logging:
  file: Edge.log
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
      
#hystrix:
 # command:
  #  default:
   #   execution:
    #    isolation:
     #     strategy: THREAD
      #    thread:
       #     timeoutInMilliseconds: 60000

ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
