info:
  component: api-gateway

server:
  port: 8765

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  cloud:
    consul:
      config:
        enabled: true
        host: localhost
        port: 8500
ribbon:
  eureka:
    enabled: false
zuul:
  ignoreLocalService: false
  #ignored-services: "*"
  routes:
    employee-producer:
      path: /api/employee-registration/**
      serviceId: employee-producer
    employee-search:
      path: /api/employee-search/**
      serviceId: employee-search
      
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
