
server:
  port: 9098
spring:
  application:
    name: employee-search
  management:
    security:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none      
      #ddl-auto: update      
  #datasource:
    #url: jdbc:postgresql://localhost:5432/hashicorp
    #username: postgres
    #password: root
