server:
  port: 8098
spring:
  application:
    name: employee-producer
management:
  security:
    enabled: false


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hashicorp
    username: postgres
    password: root
 jpa:
   generate-ddl: true
