#server port no
server:
  port: 8098

spring:
  application:
    name: employee-producer
  management:
    security:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop      
      #ddl-auto: update      
  datasource:
    url: jdbc:postgresql://localhost:5432/hashicorp
    username: postgres
    password: root

