
server:
  port: 9098
spring:
  application:
    name: employee-search
  management:
    security:
      enabled: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /api/employee-search/heartbeat-check 
        healthCheckInterval: 20s
  jpa:
    hibernate:
      ddl-auto: none      
      #ddl-auto: update      
  datasource:
    url: jdbc:postgresql://localhost:5432/hashicorp
    username: postgres
    password: root
